import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
      
    </html>
  )
}


// import {  useState } from 'react 
//  
// cconst [ count , setCount ] = useState(0)
// 
// <p>   you clicked { count  } times </p>
// onClick = {() => setCount( count + 1 )} >
//
//
//
//
//
//
//
//
//
//
//
